### ISSUE TITLE
Multiple Hubs Question

### ISSUE THREAD

**Issue by Vpxgamer** [MartenM/RedirectPlus#16]
I have 2 hubs on my minecraft server. I want to make it so if someone goes to the hub, but the main hub is not online, it will send them to another hub. How do I do this?

**Comment by MartenM** [comment]
Putting them both in the servers group in one group should do the trick.
Closed as a non issue, if you need support please go to the [spigot discussion page.](https://www.spigotmc.org/threads/redirect-plus.296461/)
