### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Tomigames** [MartenM/RedirectPlus#18]
Hi I am getting this error:

`
>.... [09:18:14] [ERROR]: java.net.UnknownHostException: www.woutdev.be
>.... [09:18:14] [ERROR]: at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
>.... [09:18:14] [ERROR]: at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
>.... [09:18:14] [ERROR]: at java.net.Socket.connect(Socket.java:607)
>.... [09:18:14] [ERROR]: at java.net.Socket.connect(Socket.java:556)
>.... [09:18:14] [ERROR]: at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
>.... [09:18:14] [ERROR]: at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
>.... [09:18:14] [ERROR]: at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
>.... [09:18:14] [ERROR]: at sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
>.... [09:18:14] [ERROR]: at sun.net.www.http.HttpClient.New(HttpClient.java:339)
>.... [09:18:14] [ERROR]: at sun.net.www.http.HttpClient.New(HttpClient.java:357)
>.... [09:18:14] [ERROR]: at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1226)
>.... [09:18:14] [ERROR]: at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1162)
>.... [09:18:14] [ERROR]: at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1056)
>.... [09:18:14] [ERROR]: at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:990)
>.... [09:18:14] [ERROR]: at be.woutdev.bungeestaffchat.updater.PluginUpdater.run(PluginUpdater.java:35)
>.... [09:18:14] [ERROR]: at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:66)
>.... [09:18:14] [ERROR]: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
>.... [09:18:14] [ERROR]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
>.... [09:18:14] [ERROR]: at java.lang.Thread.run(Thread.java:748)`

**Comment by MartenM** [comment]
This error is not caused by RedirectPlus. Please contact the author of **BungeeStaffChat** to resolve this issue @Tomigames

**Comment by Tomigames** [comment]
Sorry for the inconvenience thank you.
