### ISSUE TITLE
[Issue] Sending people to hub

### ISSUE THREAD

**Issue by socreative11** [MartenM/RedirectPlus#22]
If there are 2 players online, and the server gets restarted, one of the players goes back to the hub, the other gets kicked. (Even though I have "detect-shutdown:" enabled with a list of relevant words). How do I ensure everyone goes back to a hub?

**Comment by MartenM** [comment]
What is the kick message they receive? Also have you checked the console for output?

**Comment by MartenM** [comment]
I am closing this for now. If it happens again feel free to create a new issue.
