### ISSUE TITLE
Two servers (Skyblock And Lobby)

### ISSUE THREAD

**Issue by tnht** [MartenM/RedirectPlus#25]
Hello,

i have two servers:
- default: lobby
- skyblock

When players is on skyblock and server has crashed, players may redirect to lobby. It's ok and working good.
But if lobby has crashed, players redirect to first normal server skyblock.

It's possible?
https://pastebin.pl/view/c3eb0c45

**Comment by MartenM** [comment]
Just put them in the same server group and disable bottom kick.
Blacklist normal kick and ban messages.
