### ISSUE TITLE
WARN Error dispatching event ServerKickEvent

### ISSUE THREAD

**Issue by ishopify** [MartenM/RedirectPlus#5]
https://pastebin.com/R0U6fP32

**Comment by MartenM** [comment]
Corresponding line: `if(serverGroup.isBottomKick())` ([LINK)](https://github.com/MartenM/RedirectPlus/blob/74dc6f314227ab9e9dbf957681e196455371fa19/src/main/java/nl/martenm/redirectplus/listeners/PlayerKickListener.java#L69)

Are you sure this is not a config related issue regarding your setup?

**Comment by MartenM** [comment]
Closed due to no further information.
