### ISSUE TITLE
Placeholders for servers in redirected message

### ISSUE THREAD

**Issue by fnutt** [MartenM/RedirectPlus#7]
```
  redirected:
  - "&f"
   - "&cAn kick occurred in your connection. &cReason:&r %reason%"
   - "&cYou have been send back to the main lobby."
   - "&f"
```

It would be nice if the message could tell which server the player was moved from and to. E.g.
`"&fYou was moved from &a%from-server% &rto &a%to-server% &rbecause &a%reason%`

Thank you in advance!

**Comment by MartenM** [comment]
Sounds like a great idea. Might as well add groups and might add group display names.

**Comment by MartenM** [comment]
Implemented!

**Comment by fnutt** [comment]
Awesome. Thanks a lot for the quick implementation!
